### PR TITLE
Add android-sig

### PR DESCRIPTION
**Pull request by nkoroste**

### CODE REVIEW

**Review by Bencodes — APPROVED** [review]

**Comment by nkoroste** [comment]
@alexeagle

**Comment by alexeagle** [comment]
This is great, I'm glad to see it "formalized". @meteorcloudy could we merge it?

**Review by ahumesky — APPROVED** [review]

**Comment by ahumesky** [comment]
I don't have merge permissions, but looks good to me

**Review by meteorcloudy — APPROVED** [review]

**Review by meisterT — APPROVED** [review]

**Comment by meisterT** [comment]
Thanks!

**Pull request merged**
